name: Build LeanCal

on:
  push:
    tags:
    - "v*"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install elan
        run: |
          set -o pipefail
          curl -sSfL https://github.com/leanprover/elan/releases/download/v3.1.1/elan-x86_64-unknown-linux-gnu.tar.gz | tar xz
          ./elan-init -y --default-toolchain none
          echo "$HOME/.elan/bin" >> "${GITHUB_PATH}"

      - name: Build LeanCal
        run: sh compile.sh
      
      - name: Place dist in artifacts folder
        uses: actions/upload-artifact@v4
        with:
          name: leancal
          path: ./leancal
  
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download LeanCal artifact
        uses: actions/download-artifact@v4
        with:
          path: ./leancal
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body: "Release ${{ github.ref }}"
          files: |
            ./leancal
